import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import { FC } from 'react'

const Home: NextPage = () => {




  const Title: FC = () => {
    return(
      <div>
        <h1>Boutique Consulting & Engineering</h1>
        <h2>We consult. We innovate. We engineer.</h2>
        <button>Get Started</button>
        <div>
          <div>
            <h1>We’re changing the game.</h1>
            <h2>While everyone else plays checkers, you could be playing 4D chess. Understand your customers, competitors, capabilities, and partners. Get strategies bespoke to your business.</h2>
          </div>
        </div>
      </div>
    )
  } 

  const Services: FC = () => {
    return(
      <div>
        <h2>OUR SERVICES</h2>
        <h1>We're here to help.</h1>
        <div>
          <div>
            <img></img>
            <h1>Consulting</h1>
          </div>
          <div>
            <img></img>
            <h1>Software Development</h1>
          </div>
          <div>
            <img></img>
            <h1>Startup Resouces</h1>
          </div>
          <div>
            <img></img>
            <h1>Venture Building</h1>
          </div>
        </div>
      </div>
    )
  }

  const About: FC = () => {
    return(
      <div>
        <h2>ABOUT</h2>
        <h1>Your tursted ally.</h1>
      </div>
    )
  }

  const Team: FC = () => {
    return(
      <div>
        <h2>ABOUT</h2>
        <h1>Your tursted ally.</h1>
        <div>

        </div>
      </div>
    ) 
  }

  const Contact: FC = () => {
    return(
      <></>
    )
  }

  const Footer: FC = () => {
    return(
      <></>
    )
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Bright One Alliance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
      <Services />
      <About />
      <Team />
      <Contact />
      <Footer />
    </div>
  )
}

export default Home;